### ISSUE TITLE
Cannot select com3

### ISSUE THREAD

**Issue by Kulitorum** [slaytonrnd/CartridgeWriter#3] opened 2015-02-10 20:23 UTC
Although Arduino IDE can select my Arduino as Com3 and it's listed as com3 in Device manager, I still do not see com3 in CartridgeWriter.

Any ideas why?

**Comment by Kulitorum** [comment] 2015-02-10 20:23
Guess I should mention I'm running windows 8.1

**Comment by slaytonrnd** [comment] 2015-02-11 00:21
Hmmm, I'm not sure.  CartridgeWriter is pretty stupid in how it loads devices though, it only does it when you launch the program, so if the Arduino is plugged in after CartridgeWriter is launched or if the Arduino hasn't been fully recognized by windows yet (usually there is a sound when it is recognized) then it will not show in the list.  If you haven't tried running CartridgeWriter after verifying that you could see it in the Arduino IDE, without unplugging the Arduino, try that and see if it shows up.  It should look something like (except "COM3" in your case instead of "COM4"):

![idescreenshot](https://cloud.githubusercontent.com/assets/10148540/6139224/00c254ea-b13e-11e4-952a-0b309a49cdce.jpg)

I checked the code I was using to make sure it is ok to use in Windows 8.1 and it appears it is.  My development environment also should be ok for compiling Windows 8.1 desktop applications.

I think you may have to run CartridgeWriter with administrator privileges if your user account doesn't have them, since it is making calls to WMI.  However I think Device Manager uses the same kinds of calls so I'm guessing that is probably not the problem you are having, but something to try anyway.

I also did a little digging about Arduinos and Windows 8.1 on the web and a lot of people have had problems installing the drivers, but it sounds like you have the drivers installed correctly if you can see the device through the Arduino IDE and in Device Manager.

This may not matter, but what type of Arduino are you using and which version of the Arduino software?  I will try to get access to a Windows 8.1 machine tomorrow to see if I can reproduce your issue.

**Comment by slaytonrnd** [comment] 2015-02-11 07:12
I checked on administrator privileges by creating a non-administrator account on my Windows 7 box and it worked fine without administrator privileges so that is not it.

**Comment by Kulitorum** [comment] 2015-02-11 07:15
I'm using a Arduino Mega (1280). I tried to install VS 2013 express desktop, but was unable to load the project because it was "incompatible" - the error description was very vague, so I am now installing the full VS 2013 pro to see if that makes any difference. I also ran it as Administrator, and that made no difference too.

CartridgeWriter will allow me to select "Communications port (Com1)" but not "USB serial port (Com3)" - so I was wondering if you are filtering on the port name or someting like that?

...Waiting for VS to install....

**Comment by Kulitorum** [comment] 2015-02-11 07:21
I just swapped the ports, so my "Communications port (Com1)"  is now on com2 and the arduino on com1. This makes no difference, I can now only select "Communications port (Com2)"

**Comment by Kulitorum** [comment] 2015-02-11 08:51
After some research, it appears that Win32_SerialPort does not catch FTDI devices (the USB->serial chip on most arduinos).
I program C++ myself, so this C# business is all mumbo-jumbo to me, so I can't find a good solution, sorry. Please see what you can do, while I go find another arduino.
What Arduino do you use?

**Comment by slaytonrnd** [comment] 2015-02-11 08:58
I use an Arduino Micro.  I came across some posts about detecting FTDI through the registry so I may need to look into doing it that way if I can't find a more elegant solution.

**Comment by slaytonrnd** [comment] 2015-02-11 10:18
I committed a fix for this.  The WMI query should now include any PnP device with a name like '%(COM%)%'.  Hopefully this will catch your Arduino.  Thanks for your help in getting this figured out!

**Comment by Kulitorum** [comment] 2015-02-11 10:24
It works. Thanks :)

**Closed as completed** 2015-02-11 10:57 UTC
